DATASET_CONFIGS:
    DATASET_NAME: MNIST         # Options: [MNIST, EMNIST, CIFAR-10]
    DATASET_PATH: /mimer/NOBACKUP/Datasets/
    DATASET_DOWN: False

MODEL_CONFIGS:
    MODEL_NAME: LENET-1CH      # Options: [SIMPLE-MLP, SIMPLE-CNN, LENET-1CH, LENET-3CH, RESNET-18]
    NUM_CLASSES: 10

SAVE_PATH: ./temp/mal_weights/malicious_model_mnist.pt

TRAIN_CONFIGS:
    RUN_DEVICE: auto
    LOCAL_EPCH: 50
    BATCH_SIZE: 64
    LEARN_RATE: 0.001
    OPTIMIZER: ADAM  
    CRITERION: CROSSENTROPY         # Options: [CROSSENTROPY, NLLL]

CHANGE_CONFIGS:

    - SOURCE_LABEL: 0
      TARGET_LABEL: 8

    - SOURCE_LABEL: 8
      TARGET_LABEL: 0