FROM python:3.8-slim-buster

# update pip
RUN python3 -m pip install --upgrade pip

# setup work directory
WORKDIR /server-code

# copy the requirements file
COPY requirements.txt requirements.txt

# install requirements
RUN pip3 install -r requirements.txt

# copy the source code
COPY src .

# run the server-side code
ENTRYPOINT ["python3","run_fl_server.py"]

RUN echo "done!"