SERVER_CONFIGS:
    SERVER_TYPE: NORMAL             # Options: [NORMAL, FILTER]
    RUN_DEVICE: auto                # Options: [auto, cpu, cuda]
    AGGREGATE_STRAT: FEDAVG         # Options: [FEDAVG]
    EVALUATE_SERVER: True           # Options: [True, False]
    NUM_TRAIN_ROUND: 15
    SAMPLE_FRACTION: 1.0
    MIN_SAMPLE_SIZE: 15
    MIN_NUM_CLIENTS: 15

CLIENT_CONFIGS:
    RUN_DEVICE: auto                # Options: [auto, cpu, cuda]
    LOCAL_EPCH: 1
    BATCH_SIZE: 64
    LEARN_RATE: 0.001
    OPTIMIZER: ADAM                 # Options: [ADAM, SGD]
    CRITERION: CROSSENTROPY         # Options: [CROSSENTROPY, NLLL]

DATASET_CONFIGS:
    DATASET_NAME: CIFAR-10                              # Options: [MNIST, EMNIST, CIFAR-10]
    DATASET_PATH: /mimer/NOBACKUP/Datasets/CIFAR        # Alvis data paths: 
                                                        #       MNIST: /mimer/NOBACKUP/Datasets/
                                                        #       CIFAR: /mimer/NOBACKUP/Datasets/CIFAR
    DATASET_DOWN: False
    SPLIT: True
    DIRICHLET_ALPHA: 100.0
    WORKER_DATA: 5000               # These two options are exclusive of dirichlet data                
    CLASSES_PER_WORKER: 0           # split, and perform sampling by replacement.
    RANDOM_SEED: 333

MODEL_CONFIGS:
    MODEL_NAME: LENET-3CH          # Options: [SIMPLE-MLP, SIMPLE-CNN, LENET-1CH, LENET-3CH, RESNET-18]
    NUM_CLASSES: 10

OUTPUT_CONFIGS:
    RESULT_LOG_PATH: ./temp/run_results/
    WANDB_LOGGING: True
    WANDB_CONFIGS:
        PROJECT:  "LossLandscape"
        DIR: temp/wandb

EXPERIMENT_CONFIGS:                 # Normally used to pass configs to malicious clients
    MAL_CLIENT_FRAC: 0.0
    MAL_CLIENT_TYPE: RAND           # Options: [RAND, IRAND, MPAF, FLIP, BACK, NORM]
    MAL_HYPER_PARAM:
        # Common malicious attack configs
        ATTACK_ROUND: 3             # Rounds after which to start the malicious attack

        # IRAND specific attack configs
        IRAND_CONFIG:
            ATTACK_RATIO: 0.5
        
        # MPAF specific attack configs
        MPAF_CONFIG:
            TARGET_MODEL: ./temp/mal_weights/malicious_model_mnist.pt
            SCALE_FACTOR: 1_000_000

        # FLIP specific attack configs
        FLIP_CONFIG:
            LOCAL_EPOCHS: 5
            TARGETS:
                -   SOURCE_LABEL: 0
                    TARGET_LABEL: 8
                -   SOURCE_LABEL: 8
                    TARGET_LABEL: 0
        
        # Backdoor specific attack configs
        BACKDOOR_CONFIG:
            LOCAL_EPOCHS: 5
            TARGETS:
                -   SOURCE_LABEL: 0
                    TARGET_LABEL: 8
